name: facemask-gpu

channels:
  - conda-forge
  - anaconda
  - nvidia

dependencies:
  - python==3.8
  - opencv==4.5.1
  - cudatoolkit=11.1.74
  - cudnn=8.0.4
  - scikit-learn==0.23.2a
  - matplotlib==3.3.4
  - dvc-gdrive==2.0.5
  - pip
  - pip:
      - tensorflow-gpu==2.4.1